# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True)),
                ('start_at', models.DateTimeField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('run_type', models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled')], default='immediate', max_length=20)),
                ('max_wait_time', models.FloatField(default=100.0, help_text='In seconds', verbose_name='Maximum waiting time for completion')),
                ('state', models.CharField(choices=[('paused', 'Paused'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='paused', max_length=20)),
                ('state_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=20)),
                ('parents', models.ManyToManyField(blank=True, to='asynctaskcelery.Task', verbose_name='List of parents, can be one item')),
            ],
        ),
        migrations.AddField(
            model_name='runinstance',
            name='main_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_instances', to='asynctaskcelery.Task'),
        ),
        migrations.AddField(
            model_name='runinstance',
            name='tasks',
            field=models.ManyToManyField(to='asynctaskcelery.Task', verbose_name='List of tasks'),
        ),
        migrations.AddField(
            model_name='data',
            name='run_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='asynctaskcelery.RunInstance'),
        ),
        migrations.AddField(
            model_name='data',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='asynctaskcelery.Task'),
        ),
    ]
