# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled')], max_length=20)),
            ],
        ),
    ]
