# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asynctaskcelery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
